paths:
  /products:
    get:
      tags: [Products]
      summary: Lista todos os produtos
      responses:
        '200':
          description: Lista de produtos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

    post:
      tags: [Products]
      summary: Cria um novo produto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreate'
      responses:
        '201':
          description: Produto criado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

  /products/{id}:
    get:
      tags: [Products]
      summary: Busca produto por ID
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Produto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Produto não encontrado

components:
  schemas:
    Product:
      type: object
      properties:
        id: { type: string }
        name: { type: string, example: 'Caixa de frango congelado 20kg' }
        description: { type: string, example: 'Produto alimentício congelado' }
        supplierId: { type: string }
    ProductCreate:
      type: object
      required: [name, supplierId]
      properties:
        name: { type: string }
        description: { type: string }
        supplierId: { type: string }
